### ISSUE TITLE
Questions about the experimental environment

### ISSUE THREAD

**Issue by KyuminHwang** [GANWANSHUI/LWANet#1]
Hi, First of all thanks for your great efforts on this research.

Like AnyNet and your research (LWANet), I would like to experiment with a lightweight setting.
So, I want to get information about your experimental environment and run your research on a benchmark.

Could you please explain the experimental environment and the requirements for lightweight research?
(e.g., ubuntu version, pytorch version, CUDA version, etc.)

**Comment by GANWANSHUI** [comment]
The detailed environment could be found in https://github.com/GANWANSHUI/LWANet/blob/master/env.yaml
